### PR TITLE
Move qcow to the cloud

### PR DESCRIPTION
**Pull request by 1solomonwakhungu**
*What?*
- Move the qcow to the cloud.

*Why?*
- This will cause less burden on our local machines to read the file and will be easier to change the file when needed.

*Testing*
- I deployed a demo event with only the edge_image_location set.
- I deployed a demo event with both edge_image_location and edge_image_filename set.
- I deployed a demo event with only the edge_image_filename set.

### CODE REVIEW

**Review by jb-smoker — COMMENTED** [review]
As-is, this only supports 1 gcp-hosted qcow, named edge.qcow2. It would be nice to be support multiple versions of the qcow, referencing them by name at deploy-time.

**Comment by 1solomonwakhungu** [comment]
> As-is, this only supports 1 gcp-hosted qcow, named edge.qcow2. It would be nice to be support multiple versions of the qcow, referencing them by name at deploy-time.

What would this look like? 

Would the user specify the name of the file in the `edge_image_location` variable? Ex: "qcoq_bucket/qcow_v1.qcow2"
Or would the user specify the name of the file in a different variable called `edge_image_filename` that has a default value of edge.qcow2.

I think it would be easier to implement by introducing a new variable that the user can specify and would make the injection into the startup script more straight forward.

**Comment by jb-smoker** [comment]
> I think it would be easier to implement by introducing a new variable that the user can specify and would make the injection into the startup script more straight forward.

I agree with your solution.

**Comment by jb-smoker** [comment]
I'm sorry, I think I misunderstood what you were proposing. Let me clarify what I'm looking for:

If `edge_image_filename` is provided (a local filesystem path to an edge qcow):
- the local file provided is uploaded to the gcp bucket created by this module and copied onto the edge host from there (the original behavior)

if `edge_image_location` is provided (a gcp bucket location, ex: edge_image_location = "gs://gcp-bucket/qcow-image-name.qcow2"):
- the local file upload is skipped and the image is copied from the existing gcp bucket to the edge host from there.

I'm interested in having both local file and gcp bucket qcow hosting for this module.

**Review by jb-smoker — APPROVED** [review]
Validated with both local qcow and remote (gcp bucket-hosted) qcow. Both worked as expected. Note, the gcp compute service account must have storage.objects.get, storage.objects.list access to the hosting bucket when `edge_file_location` is used.

**Pull request merged**
